# Generated by Django 5.2.11 on 2026-03-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='outreach_variant',
            field=models.CharField(choices=[('A', 'Template A'), ('B', 'Template B')], default='A', max_length=1),
        ),
    ]
